import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Prints the "Index of the Ludus manual" section used in docs/ludus/13-reference.md:
// every article in out/support/sections.json as a Markdown bullet linking to
// https://support.ludus.com/<slug>, nested by depth under its section heading.
//
//   node manual-index.mjs > /tmp/manual-index.md
//
// Re-run after `node fetch-support.mjs` so the index matches the current manual.
const here = path.dirname(fileURLToPath(import.meta.url));
const sections = JSON.parse(fs.readFileSync(path.join(here, "out", "support", "sections.json"), "utf8"));
const decode = (t) => t
  .replace(/&#x27;|&#39;|&apos;/g, "'").replace(/&quot;/g, '"').replace(/&amp;/g, "&")
  .replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/\s+/g, " ").trim();
const md = (t) => decode(t).replace(/([\[\]])/g, "\\$1");

let count = 0;
const out = [];
for (const [section, articles] of Object.entries(sections)) {
  if (!articles.length) continue;
  out.push(`### ${md(section)}`, "");
  for (const a of articles) {
    const indent = "  ".repeat(Math.max(0, a.depth));
    out.push(`${indent}- [${md(a.title)}](https://support.ludus.com/${a.slug})`);
    count++;
  }
  out.push("");
}
out.push(`<!-- ${count} articles, generated by tools/ludus-docs/manual-index.mjs from out/support/sections.json -->`, "");
process.stdout.write(out.join("\n"));
